import { ArgType, NativeFunction } from "@tryforge/forgescript"

export default new NativeFunction({
  name: "$getVideoCaptions",
    version: "1.1.0",
  description: "Returns the available captions/subtitles for a YouTube video by its ID.",
  brackets: true,
  unwrap: true,
  args: [
    {
      name: "videoID",
      description: "The ID of the YouTube video",
      required: true,
      rest: false,
      type: ArgType.String,
    }
  ],
  output: ArgType.Json,
  async execute(ctx, [videoID]) {
    if (!ctx.client.youtube) return this.customError("YouTube API is not configured")

    const id = videoID.trim()
    if (!id) return this.customError("Video ID cannot be empty")

    const start = Date.now()
    let info
    try {
      info = await ctx.client.youtube.getInfo(id)
    } catch (e: any) {
      return this.customError("Failed to fetch video info: " + (e?.message || "unknown error"))
    }

    const captions = info?.captions?.caption_tracks || []
    const result = captions.map((c: any) => ({
      name: c.name?.text,
      languageCode: c.language_code,
      kind: c.kind,
      isAutoGenerated: c.is_translatable === false,
      url: c.url
    }))

    const ping = Date.now() - start
    return this.success(JSON.stringify({
      success: true,
      ping,
      results: result
    }, null, 2))
  }
})
